#!/bin/bash

THIS=$(cd $(dirname $0) && pwd -P)
pushd "$THIS" > /dev/null
exe=$(stack exec which gotrans)
if [ -z "$exe" ]; then
    echo "No gotrans binary found. Please invoke './build' in directory $THIS before running this script."
    exit 1
fi
popd > /dev/null

if [ "$1" == "--run" ]; then
    run=yes
    shift
else
    run=no
fi

"$exe" "$@"

if [ "$run" == "yes" ]; then
    last="${@: -1}"
    rkt=$(echo "$last" | sed 's/\.[^.]*$/.rkt/g')
    echo "Invoking racket on $rkt"
    racket "$rkt"
fi
